name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.24.5
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"
          check-latest: true
      - name: Checkout repository
        uses: actions/checkout@v4

      # jq is required by testdata/test_executable.sh
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Test
      - name: Run tests with coverage
        run: go test -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.out
