name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.0"
          cache: true
      - name: Run go vet
        run: go vet ./...

      # jq is required by testdata/test_executable.sh
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Test
      - name: Test with coverage
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.github_token }}
          file: coverage.out
          format: golang
